### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by PolinaStamenova** [PolinaStamenova/ride-fast-back-end#29]
# Setup Kanban board

Project: https://github.com/PolinaStamenova/ride-fast-back-end

We are four people in the project:

@PolinaStamenova 
@Ghiftee 
@hiromataba 
@vikitaotiz 

# Kanban board screenshot

![Kanbanboard1](https://user-images.githubusercontent.com/79217155/144280312-f79271e3-8873-47cb-a916-8e78f098af47.JPG)
![Kanbanboard2](https://user-images.githubusercontent.com/79217155/144280345-f8925e83-b836-431c-860d-473aac726eb7.JPG)
![Kanbanboard3](https://user-images.githubusercontent.com/79217155/144280360-079bf7ce-73c9-4802-bfca-9e7ca1ae171b.JPG)
![Kanbanboard4](https://user-images.githubusercontent.com/79217155/144280380-5fde855c-7055-46b3-b6dc-4a81bead5710.JPG)
![Kanbanboard5](https://user-images.githubusercontent.com/79217155/144280404-a06325d7-735e-45bf-a3cc-bd8f8bb10dbe.JPG)

**Comment by MuriloRoque** [comment]
Hi @PolinaStamenova, @vikitaotiz, @Ghiftee, @hiromataba, 

Good job so far!
There is one issue that you still need to work on but you are almost there!

## Suggested changes
- [x] Please provide a description to each task inside of each card in your Kanban board.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

```

**Comment by MuriloRoque** [comment]
Hi @PolinaStamenova, @vikitaotiz, @Ghiftee, @hiromataba, 

In my opinion, your project is approved!  There is nothing else to say other than... it's time to start :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
